version: '3.7'

services:
  app:
    image: post-hq/app-dev
    build:
      context: ./docker/dev
      args:
        UID: ${DEV_UID-501}
    ports:
      -  ${PORT:-3000}:${PORT:-3000}
    volumes:
      - ./:/var/www
    environment:
      - NODE_ENV=development
      - PORT=3000
