version: '3.7'

services:
  app:
    image: post-hq/app-dev
    build:
      context: ./docker/dev/app
      args:
        UID: ${DEV_UID-501}
    ports:
      -  ${PORT:-3000}:${PORT:-3000}
    volumes:
      - ./:/var/www
    environment:
      - NODE_ENV=development
      - PORT=3000

  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: dev
      MONGO_INITDB_DATABASE: posthq
    volumes: 
      - ./docker/dev/db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
